# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      # Config AWS credentials with Github secrets
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      # Setup virtualenv
      - name: Virtual enviroment setup
        run: pip install virtualenv
        
      # First lambda: HTML Download
      
      # Virtual enviroment setup
      - name: Lambda1 setup
        run: |
          cd lambda1/
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          deactivate
          
      
      # Clean code and Unit testing
      - name: Lambda1 flake8 and unittesting
        run: |
          cd lambda1/
          source env/bin/activate
          flake8 .
          pytest
          deactivate
      
      # AWS Update Lambda1
      - name: Lambda1 AWS update
        run: |
          cd lambda1/
          source env/bin/activate
          zappa schedule dev
          zappa update
          deactivate
          
      # Second lambda: HTML transformation into CSV
      
      # Virtual enviroment setup
      - name: Lambda2 setup
        run: |
          cd lambda2/
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
      
      # Clean code and Unit testing
      - name: Lambda2 flake8 and unittesting
        run: |
          cd lambda2/
          source env/bin/activate
          flake8 .
          pytest
          deactivate
      
      # AWS Update Lambda2
      - name: Lambda2 AWS update
        run: |
          cd lambda2/
          source env/bin/activate
          zappa update
          deactivate
      
      
          
